--
-- PostgreSQL database dump
--

-- Dumped from database version 14.8 (Debian 14.8-1.pgdg110+1)
-- Dumped by pg_dump version 14.8 (Debian 14.8-1.pgdg110+1)

-- Started on 2023-05-31 17:32:02 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3402 (class 1262 OID 17513)
-- Name: real-world-app; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE "real-world-app" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


\connect -reuse-previous=on "dbname='real-world-app'"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 209 (class 1259 OID 17514)
-- Name: article; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article (
    article_id integer NOT NULL,
    slug text NOT NULL,
    title text NOT NULL,
    description text,
    body text NOT NULL,
    fk_user_id character varying(36),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- TOC entry 210 (class 1259 OID 17521)
-- Name: article_article_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.article ALTER COLUMN article_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 17522)
-- Name: article_tag_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article_tag_mapping (
    article_tag_mapping_id integer NOT NULL,
    fk_article_id integer NOT NULL,
    fk_tag_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- TOC entry 212 (class 1259 OID 17527)
-- Name: article_tag_mapping_article_tag_mapping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.article_tag_mapping ALTER COLUMN article_tag_mapping_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_tag_mapping_article_tag_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 17528)
-- Name: article_user_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article_user_mapping (
    article_user_mapping_id integer NOT NULL,
    fk_article_id integer NOT NULL,
    favorited_by_fk_user_id character varying(36) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- TOC entry 214 (class 1259 OID 17533)
-- Name: article_user_mapping_article_user_mapping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.article_user_mapping ALTER COLUMN article_user_mapping_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_user_mapping_article_user_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 17534)
-- Name: comment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comment (
    comment_id integer NOT NULL,
    body text NOT NULL,
    fk_article_id integer NOT NULL,
    fk_user_id character varying(36) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- TOC entry 216 (class 1259 OID 17541)
-- Name: comment_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comment ALTER COLUMN comment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 17542)
-- Name: tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tag (
    tag_id integer NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- TOC entry 218 (class 1259 OID 17549)
-- Name: tag_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tag ALTER COLUMN tag_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tag_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 17550)
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    user_id character varying(36) NOT NULL,
    username character varying(255) NOT NULL,
    email character varying(255),
    bio text,
    avatar_path character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- TOC entry 220 (class 1259 OID 17557)
-- Name: user_relation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_relation (
    user_relation_id integer NOT NULL,
    fk_user_id character varying(36) NOT NULL,
    followed_by_fk_user_id character varying(36) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- TOC entry 221 (class 1259 OID 17562)
-- Name: user_relation_user_relation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_relation ALTER COLUMN user_relation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_relation_user_relation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3384 (class 0 OID 17514)
-- Dependencies: 209
-- Data for Name: article; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.article (article_id, slug, title, description, body, fk_user_id, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 3386 (class 0 OID 17522)
-- Dependencies: 211
-- Data for Name: article_tag_mapping; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.article_tag_mapping (article_tag_mapping_id, fk_article_id, fk_tag_id, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 3388 (class 0 OID 17528)
-- Dependencies: 213
-- Data for Name: article_user_mapping; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.article_user_mapping (article_user_mapping_id, fk_article_id, favorited_by_fk_user_id, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 3390 (class 0 OID 17534)
-- Dependencies: 215
-- Data for Name: comment; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.comment (comment_id, body, fk_article_id, fk_user_id, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 3392 (class 0 OID 17542)
-- Dependencies: 217
-- Data for Name: tag; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tag (tag_id, name, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 3394 (class 0 OID 17550)
-- Dependencies: 219
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."user" (user_id, username, email, bio, avatar_path, created_at, update_at) FROM stdin;
c9c01faf-4e07-4f9b-973b-1d401c36042c	testadmin	testadmin@email.com	\N	\N	2023-05-27 19:33:39.602259+00	2023-05-27 19:33:39.602259+00
\.


--
-- TOC entry 3395 (class 0 OID 17557)
-- Dependencies: 220
-- Data for Name: user_relation; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.user_relation (user_relation_id, fk_user_id, followed_by_fk_user_id, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 3403 (class 0 OID 0)
-- Dependencies: 210
-- Name: article_article_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.article_article_id_seq', 1, false);


--
-- TOC entry 3404 (class 0 OID 0)
-- Dependencies: 212
-- Name: article_tag_mapping_article_tag_mapping_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.article_tag_mapping_article_tag_mapping_id_seq', 1, false);


--
-- TOC entry 3405 (class 0 OID 0)
-- Dependencies: 214
-- Name: article_user_mapping_article_user_mapping_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.article_user_mapping_article_user_mapping_id_seq', 1, false);


--
-- TOC entry 3406 (class 0 OID 0)
-- Dependencies: 216
-- Name: comment_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.comment_comment_id_seq', 1, false);


--
-- TOC entry 3407 (class 0 OID 0)
-- Dependencies: 218
-- Name: tag_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tag_tag_id_seq', 1, false);


--
-- TOC entry 3408 (class 0 OID 0)
-- Dependencies: 221
-- Name: user_relation_user_relation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.user_relation_user_relation_id_seq', 1, false);


--
-- TOC entry 3211 (class 2606 OID 17564)
-- Name: article article_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_pkey PRIMARY KEY (article_id);


--
-- TOC entry 3215 (class 2606 OID 17566)
-- Name: article_tag_mapping article_tag_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_tag_mapping
    ADD CONSTRAINT article_tag_mapping_pkey PRIMARY KEY (article_tag_mapping_id);


--
-- TOC entry 3217 (class 2606 OID 17568)
-- Name: article_tag_mapping article_tag_mapping_unique_article_tag; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_tag_mapping
    ADD CONSTRAINT article_tag_mapping_unique_article_tag UNIQUE (fk_article_id, fk_tag_id);


--
-- TOC entry 3213 (class 2606 OID 17570)
-- Name: article article_unique_slug; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_unique_slug UNIQUE (slug);


--
-- TOC entry 3219 (class 2606 OID 17572)
-- Name: article_user_mapping article_user_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_user_mapping
    ADD CONSTRAINT article_user_mapping_pkey PRIMARY KEY (article_user_mapping_id);


--
-- TOC entry 3221 (class 2606 OID 17574)
-- Name: article_user_mapping article_user_mapping_unique_article_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_user_mapping
    ADD CONSTRAINT article_user_mapping_unique_article_user UNIQUE (fk_article_id, favorited_by_fk_user_id);


--
-- TOC entry 3223 (class 2606 OID 17576)
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (comment_id);


--
-- TOC entry 3225 (class 2606 OID 17578)
-- Name: tag tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (tag_id);


--
-- TOC entry 3227 (class 2606 OID 17580)
-- Name: tag tag_unique_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_unique_name UNIQUE (name);


--
-- TOC entry 3229 (class 2606 OID 17582)
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (user_id);


--
-- TOC entry 3233 (class 2606 OID 17586)
-- Name: user_relation user_relation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_relation
    ADD CONSTRAINT user_relation_pkey PRIMARY KEY (user_relation_id);


--
-- TOC entry 3235 (class 2606 OID 17588)
-- Name: user_relation user_relation_unique_user_follower; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_relation
    ADD CONSTRAINT user_relation_unique_user_follower UNIQUE (fk_user_id, followed_by_fk_user_id);


--
-- TOC entry 3231 (class 2606 OID 17584)
-- Name: user user_unique_username; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_unique_username UNIQUE (username);


--
-- TOC entry 3236 (class 2606 OID 17589)
-- Name: article article_fk_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_fk_user_id_fkey FOREIGN KEY (fk_user_id) REFERENCES public."user"(user_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3237 (class 2606 OID 17594)
-- Name: article_tag_mapping article_tag_mapping_fk_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_tag_mapping
    ADD CONSTRAINT article_tag_mapping_fk_article_id_fkey FOREIGN KEY (fk_article_id) REFERENCES public.article(article_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3238 (class 2606 OID 17599)
-- Name: article_tag_mapping article_tag_mapping_fk_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_tag_mapping
    ADD CONSTRAINT article_tag_mapping_fk_tag_id_fkey FOREIGN KEY (fk_tag_id) REFERENCES public.tag(tag_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3239 (class 2606 OID 17604)
-- Name: article_user_mapping article_user_mapping_favorited_by_fk_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_user_mapping
    ADD CONSTRAINT article_user_mapping_favorited_by_fk_user_id_fkey FOREIGN KEY (favorited_by_fk_user_id) REFERENCES public."user"(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3240 (class 2606 OID 17609)
-- Name: article_user_mapping article_user_mapping_fk_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_user_mapping
    ADD CONSTRAINT article_user_mapping_fk_article_id_fkey FOREIGN KEY (fk_article_id) REFERENCES public.article(article_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3241 (class 2606 OID 17614)
-- Name: comment comment_fk_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_fk_article_id_fkey FOREIGN KEY (fk_article_id) REFERENCES public.article(article_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3242 (class 2606 OID 17619)
-- Name: comment comment_fk_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_fk_user_id_fkey FOREIGN KEY (fk_user_id) REFERENCES public."user"(user_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3243 (class 2606 OID 17624)
-- Name: user_relation user_relation_fk_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_relation
    ADD CONSTRAINT user_relation_fk_user_id_fkey FOREIGN KEY (fk_user_id) REFERENCES public."user"(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3244 (class 2606 OID 17629)
-- Name: user_relation user_relation_followed_by_fk_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_relation
    ADD CONSTRAINT user_relation_followed_by_fk_user_id_fkey FOREIGN KEY (followed_by_fk_user_id) REFERENCES public."user"(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


-- Completed on 2023-05-31 17:32:03 UTC

--
-- PostgreSQL database dump complete
--

